import Header from './components/Header';
import Hero from './components/Hero';
import Section from './components/Section';
import Card from './components/Card';
import StatCard from './components/StatCard';
import Footer from './components/Footer';
import { 
  ShoppingCart, 
  Gamepad2, 
  Coins, 
  Users, 
  Cpu, 
  CreditCard, 
  Eye, 
  Link,
  TrendingUp,
  Building,
  DollarSign,
  Shield,
  Smartphone,
  AlertTriangle,
  Scale,
  UserX,
  Lock,
  Lightbulb,
  Rocket,
  Target,
  Handshake
} from 'lucide-react';

function App() {
  return (
    <div className="min-h-screen">
      <Header />
      <Hero />
      
      <Section id="overview" title="Current State & Market Overview">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <StatCard 
            number="$500M+" 
            label="Roblox Creator Earnings" 
            description="Annual revenue generated by creators through virtual item sales"
          />
          <StatCard 
            number="$9B" 
            label="Epic Games Revenue" 
            description="2021 revenue largely from cosmetic items and collaborations"
          />
          <StatCard 
            number="45M" 
            label="Travis Scott Concert" 
            description="Viewers for virtual Fortnite concert experience"
          />
          <StatCard 
            number="31M" 
            label="VR Headset Users" 
            description="Current global adoption limiting customer base"
          />
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card icon={Gamepad2} title="Gaming Platforms">
            <p>Roblox, Fortnite, and VRChat leading virtual commerce through avatar customization and virtual experiences.</p>
          </Card>
          <Card icon={Coins} title="Digital Assets">
            <p>NFTs, virtual real estate, and in-game items creating new ownership models and revenue streams.</p>
          </Card>
          <Card icon={Users} title="Social Commerce">
            <p>Virtual concerts, exclusive events, and collaborative shopping experiences driving engagement.</p>
          </Card>
          <Card icon={ShoppingCart} title="Hybrid Products">
            <p>Physical-digital combinations from Nike, Adidas creating authentic cross-reality experiences.</p>
          </Card>
        </div>
      </Section>

      <Section id="opportunities" title="Technical Infrastructure & Opportunities" dark>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          <Card icon={Cpu} title="Core Technologies" dark>
            <ul className="space-y-2">
              <li>• Extended Reality (XR) hardware</li>
              <li>• Cloud computing infrastructure</li>
              <li>• 5G networks for mobile AR</li>
              <li>• AI-powered recommendations</li>
            </ul>
          </Card>
          <Card icon={CreditCard} title="Payment Systems" dark>
            <ul className="space-y-2">
              <li>• Cryptocurrency integration</li>
              <li>• Smart contract automation</li>
              <li>• Stablecoin solutions</li>
              <li>• Traditional payment bridges</li>
            </ul>
          </Card>
          <Card icon={Eye} title="User Experience" dark>
            <ul className="space-y-2">
              <li>• Spatial interface design</li>
              <li>• Haptic feedback systems</li>
              <li>• Voice and gesture controls</li>
              <li>• Accessibility considerations</li>
            </ul>
          </Card>
        </div>

        <div className="bg-white text-black p-8 rounded-lg">
          <h3 className="text-2xl font-bold mb-6 flex items-center">
            <Link className="w-6 h-6 mr-3" />
            Interoperability Challenge
          </h3>
          <p className="text-lg mb-4">
            Digital assets purchased in one metaverse platform often cannot be used elsewhere, creating significant user friction and limiting market potential.
          </p>
          <p className="text-gray-700">
            The Metaverse Standards Forum is working toward solutions, but widespread adoption remains years away.
          </p>
        </div>
      </Section>

      <Section id="business" title="Business Implications & Market Dynamics">
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <div>
            <h3 className="text-2xl font-bold mb-6 flex items-center">
              <TrendingUp className="w-6 h-6 mr-3" />
              Market Projections
            </h3>
            <div className="space-y-4">
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">Goldman Sachs: $8 trillion opportunity</p>
                <p className="text-gray-600">Long-term metaverse economy potential</p>
              </div>
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">McKinsey: $5 trillion by 2030</p>
                <p className="text-gray-600">Conservative market size projection</p>
              </div>
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">Virtual goods: $190B by 2025</p>
                <p className="text-gray-600">Gaming and social platform driven</p>
              </div>
            </div>
          </div>
          
          <div>
            <h3 className="text-2xl font-bold mb-6 flex items-center">
              <Building className="w-6 h-6 mr-3" />
              Key Players
            </h3>
            <div className="space-y-4">
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Meta: $13B+ invested</p>
                <p className="text-gray-600">Platform leadership focus</p>
              </div>
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Microsoft: Enterprise applications</p>
                <p className="text-gray-600">Teams integration, HoloLens</p>
              </div>
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Gaming companies advantage</p>
                <p className="text-gray-600">Epic, Roblox, Unity leading</p>
              </div>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          <Card icon={DollarSign} title="Investment Requirements">
            <ul className="space-y-2">
              <li>• Simple storefronts: $50K-$200K</li>
              <li>• Branded experiences: $1M+</li>
              <li>• Virtual real estate: $100s-$Ms</li>
              <li>• Ongoing operational costs</li>
            </ul>
          </Card>
          <Card icon={Shield} title="Competitive Advantages">
            <ul className="space-y-2">
              <li>• Lower customer acquisition costs</li>
              <li>• Stronger brand engagement</li>
              <li>• No physical inventory needs</li>
              <li>• Global reach potential</li>
            </ul>
          </Card>
          <Card icon={Smartphone} title="Omnichannel Integration">
            <ul className="space-y-2">
              <li>• Parallel to traditional commerce</li>
              <li>• Enhanced customer touchpoints</li>
              <li>• Cross-platform experiences</li>
              <li>• Data-driven personalization</li>
            </ul>
          </Card>
        </div>
      </Section>

      <Section id="challenges" title="Challenges & Limitations" dark>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
          <Card icon={AlertTriangle} title="Technical Barriers" dark>
            <ul className="space-y-2">
              <li>• Expensive, bulky hardware</li>
              <li>• Motion sickness (25-40% users)</li>
              <li>• High network requirements</li>
              <li>• Limited battery life</li>
            </ul>
          </Card>
          <Card icon={Scale} title="Regulatory Issues" dark>
            <ul className="space-y-2">
              <li>• Unclear digital asset ownership</li>
              <li>• Consumer protection gaps</li>
              <li>• Data privacy compliance</li>
              <li>• Tax implications uncertainty</li>
            </ul>
          </Card>
          <Card icon={UserX} title="Adoption Barriers" dark>
            <ul className="space-y-2">
              <li>• Digital literacy requirements</li>
              <li>• High cost barriers</li>
              <li>• Value perception challenges</li>
              <li>• Social acceptance varies</li>
            </ul>
          </Card>
          <Card icon={Lock} title="Security Concerns" dark>
            <ul className="space-y-2">
              <li>• Avatar hijacking risks</li>
              <li>• Biometric data collection</li>
              <li>• Smart contract vulnerabilities</li>
              <li>• Platform dependency risks</li>
            </ul>
          </Card>
        </div>

        <div className="bg-white text-black p-8 rounded-lg">
          <h3 className="text-2xl font-bold mb-4">Critical Success Factors</h3>
          <p className="text-lg mb-4">
            Success requires balancing innovation with practicality, focusing on genuine customer value rather than technological novelty.
          </p>
          <p className="text-gray-700">
            Businesses must maintain flexibility as platforms, technologies, and consumer preferences continue to rapidly evolve.
          </p>
        </div>
      </Section>

      <Section id="future" title="Future Outlook & Strategic Recommendations">
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <div>
            <h3 className="text-2xl font-bold mb-6 flex items-center">
              <Lightbulb className="w-6 h-6 mr-3" />
              3-5 Year Predictions
            </h3>
            <div className="space-y-4">
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">Hardware Advancement</p>
                <p className="text-gray-600">Lighter, affordable VR/AR devices reaching $200-$400 by 2027-2028</p>
              </div>
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">AI Integration</p>
                <p className="text-gray-600">Sophisticated virtual assistants and automated content generation</p>
              </div>
              <div className="border-l-4 border-black pl-4">
                <p className="font-semibold">Regulatory Frameworks</p>
                <p className="text-gray-600">Clearer guidelines for virtual asset ownership and taxation</p>
              </div>
            </div>
          </div>
          
          <div>
            <h3 className="text-2xl font-bold mb-6 flex items-center">
              <Rocket className="w-6 h-6 mr-3" />
              Emerging Trends
            </h3>
            <div className="space-y-4">
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Sustainability Focus</p>
                <p className="text-gray-600">Virtual products as alternatives to physical consumption</p>
              </div>
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Social Commerce</p>
                <p className="text-gray-600">Collaborative and community-driven shopping experiences</p>
              </div>
              <div className="bg-gray-100 p-4 rounded-lg">
                <p className="font-semibold">Hybrid Retail</p>
                <p className="text-gray-600">Physical stores with AR overlays becoming dominant</p>
              </div>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          <Card icon={Target} title="Experimental Approach">
            <p className="mb-3">Start with small-scale pilot projects to understand customer behavior without major capital commitments.</p>
            <p>Platform diversification reduces dependency risks while maximizing reach.</p>
          </Card>
          <Card icon={Handshake} title="Partnership Strategies">
            <p className="mb-3">Collaborate with existing platforms, technology providers, and content creators to accelerate entry.</p>
            <p>Cross-industry partnerships create unique value propositions.</p>
          </Card>
          <Card icon={Users} title="Customer Education">
            <p className="mb-3">Invest in user onboarding and education programs for less tech-savvy demographics.</p>
            <p>Free experiences and trials overcome initial skepticism.</p>
          </Card>
        </div>

        <div className="mt-12 bg-black text-white p-8 rounded-lg">
          <h3 className="text-2xl font-bold mb-4">Strategic Conclusion</h3>
          <p className="text-lg mb-4">
            The metaverse represents a fundamental shift in consumer-brand interaction. While current limitations are significant, mainstream adoption appears inevitable.
          </p>
          <p className="text-gray-300">
            Businesses that begin strategic experimentation now, while maintaining realistic expectations about timelines and challenges, will be best positioned to capitalize on this emerging opportunity.
          </p>
        </div>
      </Section>

      <Footer />
    </div>
  );
}

export default App;